###

POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Teste 02",
    "description": "Não sei se é uma descrição!",
    "duration": 555552}

###

GET http://localhost:3333/videos


###

PUT http://localhost:3333/videos/710ce1a0-b8ea-41fa-a2c9-c253ce5dd3e8
Content-Type: application/json

{
    "title": "Este era o teste_02",
    "description": "Agora tenho certeza que isso é uma descrição!",
    "duration": 360
}

###

DELETE http://localhost:3333/videos/710ce1a0-b8ea-41fa-a2c9-c253ce5dd3e8