###

POST http://localhost:3333/videos
Content-Type: application/json

{
    "title": "Teste 01",
    "description": "É uma descrição!",
    "duration": 392383
}

###

GET http://localhost:3333/videos


###

PUT http://localhost:3333/videos/
Content-Type: application/json

{
    "title": "titulo_que_não_é_mais_titulo",
    "description": "essa não é mais minha descrição",
    "duration": 30
}

###

DELETE http://localhost:3333/videos/289fd54b-4319-4db6-a7d1-8e23b6b47050